version: '3'

services:
  bot:
    build: .
    volumes:
      - ./src/:/usr/app/src/
    env_file: .env
    environment:
      - COMMIT_HASH=${COMMIT_HASH}
    depends_on:
      - lavalink
  lavalink:
    ports:
      - 2334:2334
    image: ghcr.io/freyacodes/lavalink:3
    volumes:
      - ./lavalink/application.yaml:/opt/Lavalink/application.yaml
