version: '3'

services:
  bot:
    build: .
    volumes:
      - ./cmds:/usr/app/cmds
    env_file: .env
    depends_on:
      - lavalink
  lavalink:
    ports:
      - 2334:2334
    image: ghcr.io/freyacodes/lavalink:3
    volumes:
      - ./lavalink/application.yaml:/opt/Lavalink/application.yaml
