version: '3'

services:
  bot:
    build: .
    env_file: .env
    environment:
      - COMMIT_HASH=${COMMIT_HASH}
    depends_on:
      - lavalink
  lavalink:
    image: ghcr.io/freyacodes/lavalink:3
    volumes:
      - ./lavalink/application.yaml:/opt/Lavalink/application.yaml
