# This is a basic workflow to help you get started with Actions

name: Deploy
# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "~/mosquitao-prod"

      - name: Setup .env
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ~/mosquitao-prod
            echo "MosquitaoToken=${{ secrets.BOT_TOKEN }}" > .env
            echo "OWNER_ID=${{ secrets.OWNER_ID }}" >> .env
            echo "REDDIT_ID=${{ secrets.REDDIT_ID }}" >> .env
            echo "REDDIT_SECRET=${{ secrets.REDDIT_SECRET }}" >> .env
            echo "REDDIT_AGENT=${{ secrets.REDDIT_AGENT }}" >> .env
            echo "DETA_KEY=${{ secrets.DETA_KEY }}" >> .env
            echo "YT_REFRESH_TOKEN"=${{ secrets.YT_REFRESH_TOKEN }} >> .env
            echo "YT_PLAYLIST"=${{ secrets.YT_PLAYLIST }} >> .env
            echo "YT_CLIENT_ID"=${{ secrets.YT_CLIENT_ID }} >> .env
            echo "YT_CLIENT_SECRET"=${{ secrets.YT_CLIENT_SECRET }} >> .env
            echo "SPOTIFY_ID"=${{ secrets.SPOTIFY_ID }} >> .env
            echo "SPOTIFY_SECRET"=${{ secrets.SPOTIFY_SECRET }} >> .env

      - name: Run deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ~/mosquitao-prod
            ./mosquitao-boot.sh
